server:
  port: 8110

spring:
  profiles:
    active: dev
  application:
    name: service_edu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db20_guli_edu?serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#logging:
#  level:
#    root: ERROR


#spring:

cloud:
  nacos:
    discovery:
      server-addr: localhost:8848 # nacos服务地址